/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function transform(code: string): string
export declare function transformGfm(code: string): string
export interface MdxOptions {
  development?: boolean
  providerImportSource?: string
  jsx?: boolean
  jsxImportSource?: string
  pragma?: string
  pragmaFrag?: string
  pragmaImportSource?: string
  filepath?: string
  jsxRuntime?: "classic" | "automatic"
}
export declare function transformMdx(code: string, options?: MdxOptions | undefined | null): string
